# Generated by Django 4.2.7 on 2024-05-20 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='City',
            new_name='city',
        ),
    ]
